# NumPy Tutorial Work

In [6]:
import numpy as np
a = np.arange(15).reshape(3,5)
print(a)
print(a.ndim)

b = np.array([3, 5, 1])
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
2
[3 5 1]


In [14]:
a = np.array([0, 2, 5])
print(a.dtype)
b = np.array([1.0, 1.2, 1.5])
print(b.dtype)

c = np.array([a, b])
print(c)
print(c.dtype)

d = np.array(c, dtype=complex)
print(d)

int64
float64
[[0.  2.  5. ]
 [1.  1.2 1.5]]
float64
[[0. +0.j 2. +0.j 5. +0.j]
 [1. +0.j 1.2+0.j 1.5+0.j]]


In [20]:
print(np.zeros((4,5)))
print(np.zeros((3,2,5), dtype=np.int16))
print(np.empty((2,3)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
# 0.3 gap between numbers
print(np.arange(0, 2, 0.3))
# 9 numbers; preferable
print(np.linspace(0, 2, 9))

[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [31]:
x = np.array([*a, *b, *a, *b])
print(x)
x = x.reshape(2,3,2)
print(x)
x = x.reshape(3,4)
print(x)

[0.  2.  5.  1.  1.2 1.5 0.  2.  5.  1.  1.2 1.5]
[[[0.  2. ]
  [5.  1. ]
  [1.2 1.5]]

 [[0.  2. ]
  [5.  1. ]
  [1.2 1.5]]]
[[0.  2.  5.  1. ]
 [1.2 1.5 0.  2. ]
 [5.  1.  1.2 1.5]]


In [34]:
a = np.array([20,30,40,50])
b = np.arange(4)

c = a - b
print(c)
print(b**2)
10*np.cos(b)
c<35

[20 29 38 47]
[0 1 4 9]


array([ True,  True, False, False])

In [35]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print(A * B)
print(A @ B)
print(A.dot(B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [42]:
a = np.random.random((2,3))
print(a)
print(a.sum())
print(a.min())
try:
    print(min(a))
except ValueError as e:
    print(e)
print(a.max())

[[0.42844857 0.09648259 0.36830917]
 [0.83556505 0.25890951 0.40817192]]
2.3958868103211652
0.09648258716480596
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
0.8355650477510541


In [43]:
b = np.arange(12).reshape(3,4)
print(b)
print(b.sum(axis=0))
print(b.min(axis=1))
print(b.cumsum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [53]:
b = np.arange(3)
print(b)
print(np.exp(b))
print(np.sqrt(b))

print(b[:int(len(b)/2)])

def f(x,y):
    return 20 * (x+y)

b = np.fromfunction(f, (4,5), dtype=int)
print(b)
print(b[2,3])
print(b[2])
print(b[2,:])
print(b[-1])
print(b[-1,:])
print(b[2,...])

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[0]
[[  0  20  40  60  80]
 [ 20  40  60  80 100]
 [ 40  60  80 100 120]
 [ 60  80 100 120 140]]
100
[ 40  60  80 100 120]
[ 40  60  80 100 120]
[ 60  80 100 120 140]
[ 60  80 100 120 140]
[ 40  60  80 100 120]


In [57]:
A = np.zeros((3,4))
print(A)
print(A.T)
print(A.ravel())

# reshape returns new array, resize modifies inplace
# dimension length of -1 auto adjusts

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [63]:
a = np.zeros((2,2))
b = np.fromfunction(f, (2,2), dtype=int)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

print(np.column_stack((a,b)))
print(b[:,np.newaxis])

np.hsplit(b,2)

[[ 0.  0.]
 [ 0.  0.]
 [ 0. 20.]
 [20. 40.]]
[[ 0.  0.  0. 20.]
 [ 0.  0. 20. 40.]]
[[ 0.  0.  0. 20.]
 [ 0.  0. 20. 40.]]
[[[ 0 20]]

 [[20 40]]]


[array([[ 0],
        [20]]),
 array([[20],
        [40]])]

In [65]:
c = b.copy()
print(b == c)
print(b is c)

[[ True  True]
 [ True  True]]
False


In [66]:
a = np.arange(int(1e8))
# this is good
b = a[:100].copy()
del a

# arrays as indices are weird
# ix_ is useful for combinatorics

In [72]:
b = np.fromfunction(f, (5,5), dtype=int)
print(b)
a = b <= 100
print(a)
print(b[a])
b[a] = 0
print(b)

[[  0  20  40  60  80]
 [ 20  40  60  80 100]
 [ 40  60  80 100 120]
 [ 60  80 100 120 140]
 [ 80 100 120 140 160]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True False]
 [ True  True  True False False]
 [ True  True False False False]]
[  0  20  40  60  80  20  40  60  80 100  40  60  80 100  60  80 100  80
 100]
[[  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0 120]
 [  0   0   0 120 140]
 [  0   0 120 140 160]]
